name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform and OpenTofu Validate, Format, Plan, Security
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cli: [terraform, opentofu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        if: matrix.cli == 'terraform'
        uses: hashicorp/setup-terraform@v2

      - name: Set up OpenTofu
        if: matrix.cli == 'opentofu'
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Format Check
        run: ${{ matrix.cli }} fmt -check -recursive

      - name: Init & Validate (root)
        run: |
          ${{ matrix.cli }} init
          ${{ matrix.cli }} validate

      - name: Init & Validate (iam-user example)
        working-directory: examples/iam-user
        run: |
          ${{ matrix.cli }} init
          ${{ matrix.cli }} validate

      - name: Plan (iam-user example)
        working-directory: examples/iam-user
        run: ${{ matrix.cli }} plan -no-color

      - name: Init & Validate (cross-account-role example)
        working-directory: examples/cross-account-role
        run: |
          ${{ matrix.cli }} init
          ${{ matrix.cli }} validate

      - name: Plan (cross-account-role example)
        working-directory: examples/cross-account-role
        run: ${{ matrix.cli }} plan -no-color

      - name: Run Checkov (root)
        if: matrix.cli == 'terraform'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: true

      - name: Run Checkov (iam-user example)
        if: matrix.cli == 'terraform'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/iam-user
          quiet: true
          soft_fail: true

      - name: Run Checkov (cross-account-role example)
        if: matrix.cli == 'terraform'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/cross-account-role
          quiet: true
          soft_fail: true
